version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: catherinepope/mac
    steps:
      - run: echo "Hi I'm hopefully running on Runners!"
